### ISSUE TITLE
Error: Feed is closed

### ISSUE THREAD

**Issue by ryanramage** [RangerMauve/dat-gateway#18]
I was testing this out on my server, I got this

I have not investigated very much, but just wanted to raise this if it is helpful

```
[dat-gateway] Now listening on port 3000
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Feed is closed
    at Feed._onclose (/usr/lib/node_modules/dat-gateway/node_modules/hypercore/index.js:1092:34)
    at /usr/lib/node_modules/dat-gateway/node_modules/hypercore/index.js:1082:38
    at Request.done [as _callback] (/usr/lib/node_modules/dat-gateway/node_modules/hypercore/lib/storage.js:203:5)
    at Request.callback (/usr/lib/node_modules/dat-gateway/node_modules/random-access-storage/index.js:161:8)
    at nextTickCallback (/usr/lib/node_modules/dat-gateway/node_modules/random-access-storage/index.js:249:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by RangerMauve** [comment]
Oh snap. I thought this was already accounted for in [this code](https://github.com/RangerMauve/dat-gateway/blob/master/index.js#L123). Would you mind double-checking that you have the latest version installed?

**Comment by ryanramage** [comment]
I have 2.0.1-beta installed from npm but it looks like the code you pointed me to is not published to npm.

Oh, I think I see the issue, @garbados is the only author on npm. Any chance @garbados you add a collaborator (rangermauve) ? 

Would you be able to do a version bump and publish to npm?

For now I will just run from the git repo

**Comment by RangerMauve** [comment]
Yeah, sorry, I should have made the docs more clear. 😅 I was going to merge with garbados a while ago, but I kinda lagged on the unit tests and haven't had time to polish it since.

Hopefully I'll get around to cleaning it up a bit and setting up tests so it can be merged back in.

For now it works fine if you install it from my github repo.

**Comment by garbados** [comment]
@RangerMauve I certainly wouldn't mind making you a collaborator on GitHub and on NPM. We should probably talk to pfrazee about getting permissions upstream, too.

**Comment by RangerMauve** [comment]
Yeah, that would be awesome. :D The less forks the better.
