### ISSUE TITLE
Error: read ECONNRESET when refreshing the browser

### ISSUE THREAD

**Issue by chrisekelley** [RangerMauve/dat-gateway#4]
I've created a small webapp to test out the dat-archive-web API. When I refresh the browsder, it throw this error and kills the node process: Here is the error message:

```
[dat-gateway] Now listening on port 3000
[dat-librarian] Adding archive from 528691905866112c90eea949bcc0712c208f0ac0803d38312dc18cfa7fda82d1
[dat-librarian] Archive 528691905866112c90eea949bcc0712c208f0ac0803d38312dc18cfa7fda82d1 already in cache.
[dat-gateway] Adding HTTP handler to archive...
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TCP.onread (net.js:623:25)
```

I'm running this via bunsen's www/nodejs_project/index.js app, which launches a version of DatGateway with an extra switch:

```
const datGatewayName = 'dat-gateway';
const max = 20;
const period = 60 * 1000 // every minute
const port = 3000
const ttl = 43200 * 60 * 1000 // 30 days
const dat = {temp:false}
const redirect = true

var dir = path.join(__dirname, datGatewayName)
console.log("redirect: " + redirect)
mkdirp.sync(dir) // make sure it exists
const gateway = new DatGateway({ dir, dat, max, period, ttl, redirect })
gateway
    .load()
    .then(() => {
        return gateway.listen(port)
    })
    .then(function () {
        console.log('[dat-gateway] Now listening on port ' + port)
    })
    .catch(console.error)
```

I've already got a fix for this, which I'll send in a PR.

**Comment by chrisekelley** [comment]
All is good - your recent merge resolves this issue. Thanks!
